[package]
name = "rustorm"
version = "0.0.8"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "An ORM for rust"
readme = "README.md"
repository = "https://github.com/ivanceras/rustorm"
documentation = "https://ivanceras.github.io/rustorm/rustorm/"
keywords = ["orm", "database", "sql"]

[lib]
name = "rustorm"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]

[dependencies.postgres]
version = "*"
features = ["time", "uuid", "chrono"]


[dependencies.r2d2_sqlite]
path = "../r2d2-sqlite"


[dependencies]
rustc-serialize = "*"
uuid = "*"
log = "*"
env_logger = "*"
regex = "*"
url = "*"
time = "*"
r2d2 = "*"
r2d2_postgres = "*"
rusqlite = "*"
mysql = "*"
